import { GoogleGenAI } from '@google/genai';
import type { ImageAspectRatio, ImageGenerateResult, ImageReference, TextGenerateOptions } from './types.js';

export async function generateText(
  apiKey: string,
  model: string,
  prompt: string,
  options?: TextGenerateOptions
): Promise<string> {
  const ai = new GoogleGenAI({ apiKey });
  const response = await ai.models.generateContent({
    model,
    contents: prompt,
    config: options?.jsonMode ? { responseMimeType: 'application/json' } : undefined,
  });
  return response.text || '';
}

export async function generateImage(
  apiKey: string,
  model: string,
  prompt: string,
  references?: ImageReference[],
  aspectRatio?: ImageAspectRatio
): Promise<ImageGenerateResult> {
  const ai = new GoogleGenAI({ apiKey });
  const requestParts = [
    ...(references || []).map((ref) => ({ inlineData: { mimeType: ref.mimeType, data: ref.data } })),
    { text: prompt },
  ];
  const response = await ai.models.generateContent({
    model,
    contents: { parts: requestParts },
    config: {
      imageConfig: { aspectRatio: aspectRatio || '1:1' },
    },
  });

  const responseParts = response.candidates?.[0]?.content?.parts || [];
  for (const part of responseParts) {
    if (part.inlineData?.data) {
      const mimeType = part.inlineData.mimeType || 'image/png';
      return {
        imageUrl: `data:${mimeType};base64,${part.inlineData.data}`,
        refinedPrompt: prompt,
      };
    }
  }

  throw new Error('No image generated by the model. It may have been filtered.');
}
