import OpenAI, { toFile } from 'openai';
import type { ImageAspectRatio, ImageGenerateResult, ImageReference, TextGenerateOptions } from './types.js';

export async function generateText(
  apiKey: string,
  model: string,
  prompt: string,
  options?: TextGenerateOptions
): Promise<string> {
  const client = new OpenAI({ apiKey });
  const response = await client.chat.completions.create({
    model,
    messages: [{ role: 'user', content: prompt }],
    ...(options?.jsonMode ? { response_format: { type: 'json_object' as const } } : {}),
  });
  return response.choices[0]?.message?.content || '';
}

const EXT_BY_MIME: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/jpg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
};

const GPT_IMAGE_SIZE_BY_RATIO: Record<ImageAspectRatio, '1024x1024' | '1024x1536'> = {
  '1:1': '1024x1024',
  '9:16': '1024x1536',
};

const DALL_E_SIZE_BY_RATIO: Record<ImageAspectRatio, '1024x1024' | '1024x1792'> = {
  '1:1': '1024x1024',
  '9:16': '1024x1792',
};

export async function generateImage(
  apiKey: string,
  model: string,
  prompt: string,
  references?: ImageReference[],
  aspectRatio?: ImageAspectRatio
): Promise<ImageGenerateResult> {
  const client = new OpenAI({ apiKey });

  if (model === 'gpt-image-1') {
    const size = GPT_IMAGE_SIZE_BY_RATIO[aspectRatio || '1:1'];
    if (references && references.length) {
      const images = await Promise.all(references.map((ref, i) => {
        const ext = EXT_BY_MIME[ref.mimeType] || 'png';
        return toFile(Buffer.from(ref.data, 'base64'), `reference-${i}.${ext}`, { type: ref.mimeType });
      }));
      const response = await client.images.edit({
        model: 'gpt-image-1',
        image: images,
        prompt,
        size,
      });
      const b64 = response.data?.[0]?.b64_json;
      if (!b64) throw new Error('No image generated by GPT Image model.');
      return {
        imageUrl: `data:image/png;base64,${b64}`,
        refinedPrompt: prompt,
      };
    }

    const response = await client.images.generate({
      model: 'gpt-image-1',
      prompt,
      size,
    });
    const b64 = response.data?.[0]?.b64_json;
    if (!b64) throw new Error('No image generated by GPT Image model.');
    return {
      imageUrl: `data:image/png;base64,${b64}`,
      refinedPrompt: prompt,
    };
  }

  const response = await client.images.generate({
    model: 'dall-e-3',
    prompt,
    size: DALL_E_SIZE_BY_RATIO[aspectRatio || '1:1'],
    response_format: 'b64_json',
  });

  const b64 = response.data?.[0]?.b64_json;
  if (!b64) throw new Error('No image generated by DALL-E.');
  return {
    imageUrl: `data:image/png;base64,${b64}`,
    refinedPrompt: prompt,
  };
}
